const STEPS = {
    NONE: 'NONE',
    PROCESS_STARS_LIST: 'PROCESS_STARS_LIST',
    PROCESS_STAR: 'PROCESS_STAR',
    PROCESS_PLANETS_LIST: 'PROCESS_PLANETS_LIST',
    PROCESS_PLANET: 'PROCESS_PLANET',
    PROCESS_TREASURES_LIST: 'PROCESS_TREASURES_LIST',
    PROCESS_TREASURE: 'PROCESS_TREASURE',
    PROCESS_TREASURE_ID: 'PROCESS_TREASURE_ID',
};

module.exports = STEPS;
